
<head>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
</style>
</head>

<form id="form1" runat="server">
	<p class="auto-style1">
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConnectionString="Data Source=DEEPEDDY\DEEPEDDYSQL;Initial Catalog=GACUSTOMER;User ID=sa;Password=*Columbia1" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [adminid], [custadminalpha], [userid], [userfullname], [loginid], [password1] FROM [custadmins]" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM [custadmins] WHERE [adminid] = @original_adminid AND (([custadminalpha] = @original_custadminalpha) OR ([custadminalpha] IS NULL AND @original_custadminalpha IS NULL)) AND [userid] = @original_userid AND (([userfullname] = @original_userfullname) OR ([userfullname] IS NULL AND @original_userfullname IS NULL)) AND (([loginid] = @original_loginid) OR ([loginid] IS NULL AND @original_loginid IS NULL)) AND (([password1] = @original_password1) OR ([password1] IS NULL AND @original_password1 IS NULL))" InsertCommand="INSERT INTO [custadmins] ([custadminalpha], [userid], [userfullname], [loginid], [password1]) VALUES (@custadminalpha, @userid, @userfullname, @loginid, @password1)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [custadmins] SET [custadminalpha] = @custadminalpha, [userid] = @userid, [userfullname] = @userfullname, [loginid] = @loginid, [password1] = @password1 WHERE [adminid] = @original_adminid AND (([custadminalpha] = @original_custadminalpha) OR ([custadminalpha] IS NULL AND @original_custadminalpha IS NULL)) AND [userid] = @original_userid AND (([userfullname] = @original_userfullname) OR ([userfullname] IS NULL AND @original_userfullname IS NULL)) AND (([loginid] = @original_loginid) OR ([loginid] IS NULL AND @original_loginid IS NULL)) AND (([password1] = @original_password1) OR ([password1] IS NULL AND @original_password1 IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_adminid" Type="Int32" />
			<asp:Parameter Name="original_custadminalpha" Type="String" />
			<asp:Parameter Name="original_userid" Type="Int32" />
			<asp:Parameter Name="original_userfullname" Type="String" />
			<asp:Parameter Name="original_loginid" Type="String" />
			<asp:Parameter Name="original_password1" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="custadminalpha" Type="String" />
			<asp:Parameter Name="userid" Type="Int32" />
			<asp:Parameter Name="userfullname" Type="String" />
			<asp:Parameter Name="loginid" Type="String" />
			<asp:Parameter Name="password1" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="custadminalpha" Type="String" />
			<asp:Parameter Name="userid" Type="Int32" />
			<asp:Parameter Name="userfullname" Type="String" />
			<asp:Parameter Name="loginid" Type="String" />
			<asp:Parameter Name="password1" Type="String" />
			<asp:Parameter Name="original_adminid" Type="Int32" />
			<asp:Parameter Name="original_custadminalpha" Type="String" />
			<asp:Parameter Name="original_userid" Type="Int32" />
			<asp:Parameter Name="original_userfullname" Type="String" />
			<asp:Parameter Name="original_loginid" Type="String" />
			<asp:Parameter Name="original_password1" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
	<img alt="GALOGO" height="254" src="../images/Greenvillassociates.jpg" width="441"></p>
	<p class="auto-style1">account.greenvilleassociates.com</p>
	<p class="auto-style1">ADMIN LIST</p>
	<asp:GridView id="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="adminid" Width="784px">
		<Columns>
			<asp:BoundField DataField="adminid" HeaderText="adminid" SortExpression="adminid" InsertVisible="False" ReadOnly="True">
			</asp:BoundField>
			<asp:BoundField DataField="custadminalpha" HeaderText="custadminalpha" SortExpression="custadminalpha">
			</asp:BoundField>
			<asp:BoundField DataField="userid" HeaderText="userid" SortExpression="userid">
			</asp:BoundField>
			<asp:BoundField DataField="userfullname" HeaderText="userfullname" SortExpression="userfullname">
			</asp:BoundField>
			<asp:BoundField DataField="loginid" HeaderText="loginid" SortExpression="loginid">
			</asp:BoundField>
			<asp:BoundField DataField="password1" HeaderText="password1" SortExpression="password1">
			</asp:BoundField>
		</Columns>
	</asp:GridView>
</form>
