
<head>
<style type="text/css">
.auto-style1 {
	text-align: center;
}
.auto-style2 {
	text-align: center;
	text-decoration: underline;
}
</style>
</head>

<form id="form1" runat="server">
	<p class="auto-style1">
	<asp:SqlDataSource id="SqlDataSource1" runat="server" ConnectionString="Data Source=DEEPEDDY\DEEPEDDYSQL;Initial Catalog=GACUSTOMER;User ID=sa;Password=*Columbia1" ProviderName="System.Data.SqlClient" SelectCommand="SELECT [logoid], [custid], [url1], [logotype] FROM [logo]" ConflictDetection="CompareAllValues" DeleteCommand="DELETE FROM [logo] WHERE [logoid] = @original_logoid AND (([custid] = @original_custid) OR ([custid] IS NULL AND @original_custid IS NULL)) AND (([url1] = @original_url1) OR ([url1] IS NULL AND @original_url1 IS NULL)) AND (([logotype] = @original_logotype) OR ([logotype] IS NULL AND @original_logotype IS NULL))" InsertCommand="INSERT INTO [logo] ([custid], [url1], [logotype]) VALUES (@custid, @url1, @logotype)" OldValuesParameterFormatString="original_{0}" UpdateCommand="UPDATE [logo] SET [custid] = @custid, [url1] = @url1, [logotype] = @logotype WHERE [logoid] = @original_logoid AND (([custid] = @original_custid) OR ([custid] IS NULL AND @original_custid IS NULL)) AND (([url1] = @original_url1) OR ([url1] IS NULL AND @original_url1 IS NULL)) AND (([logotype] = @original_logotype) OR ([logotype] IS NULL AND @original_logotype IS NULL))">
		<DeleteParameters>
			<asp:Parameter Name="original_logoid" Type="Int32" />
			<asp:Parameter Name="original_custid" Type="Int32" />
			<asp:Parameter Name="original_url1" Type="String" />
			<asp:Parameter Name="original_logotype" Type="String" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="custid" Type="Int32" />
			<asp:Parameter Name="url1" Type="String" />
			<asp:Parameter Name="logotype" Type="String" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="custid" Type="Int32" />
			<asp:Parameter Name="url1" Type="String" />
			<asp:Parameter Name="logotype" Type="String" />
			<asp:Parameter Name="original_logoid" Type="Int32" />
			<asp:Parameter Name="original_custid" Type="Int32" />
			<asp:Parameter Name="original_url1" Type="String" />
			<asp:Parameter Name="original_logotype" Type="String" />
		</UpdateParameters>
	</asp:SqlDataSource>
	<img alt="GALOGO" height="254" src="../images/Greenvillassociates.jpg" width="441"></p>
	<p class="auto-style1">account.greenvilleassociates.com</p>
	<p class="auto-style2">CUSTOMER LOGO INFORMATION</p>
	<div class="auto-style1">
	<asp:GridView id="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataSourceID="SqlDataSource1" Width="777px" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" DataKeyNames="logoid">
		<Columns>
			<asp:BoundField DataField="logoid" HeaderText="logoid" InsertVisible="False" ReadOnly="True" SortExpression="logoid">
			</asp:BoundField>
			<asp:BoundField DataField="custid" HeaderText="custid" SortExpression="custid">
			</asp:BoundField>
			<asp:BoundField DataField="url1" HeaderText="url1" SortExpression="url1">
			</asp:BoundField>
			<asp:BoundField DataField="logotype" HeaderText="logotype" SortExpression="logotype">
			</asp:BoundField>
		</Columns>
	</asp:GridView>
	</div>
</form>
